# Site settings
author: Huda Yousif
title: Here We go! 
header-img: img/home-bg.png
email: hjdoski@gmail.com
copyright_name: Huda Yousif
description: > # this means to ignore newlines until "baseurl:"
  Start of a new journey 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yousifhj

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
